#!/bin/sh

export SRC=$TMPOS/sources
export BUILD=$TMPOS/sources/build

#clean build dirs 
function ebuild_clean()
{
cd $BUILD
rm -rvf $BUILD/* 
}

###############################################################################
5.5. Linux-Headers-3.2.6 
------------------------------------

tar -xvpf $SRC/linux-3.2.6.tar.xz -C $BUILD
cd $BUILD/linux-3.2.6/

install -dv /tools/include
make mrproper
make ARCH=x86_64 headers_check
make ARCH=x86_64 INSTALL_HDR_PATH=dest headers_install
cp -rv dest/include/* /tools/include

ebuild_clean

#################################################################################
5.6. File-5.10 
------------------------------------

tar -xvpf $SRC/file-5.10.tar.gz -C $BUILD
cd $BUILD/file-5.10

./configure --prefix=/cross-tools
make -j32
make install

cd $BUILD
rm -rvf $BUILD/*

#################################################################################

5.26. M4-1.4.16
------------------------------------

tar -xvpf $SRC/m4-1.4.16.tar.bz2 -C $BUILD
cd $BUILD/m4-1.4.16

./configure --prefix=/cross-tools
make -j32
make install

cd $BUILD
rm -rvf $BUILD/*

#################################################################################
5.8. Ncurses-5.9 
------------------------------------

tar -xvpf $SRC/ncurses-5.9.tar.gz -C $BUILD
cd $BUILD/ncurses-5.9

patch -Np1 -i ../ncurses-5.9-bash_fix-1.patch
./configure --prefix=/cross-tools --without-debug --without-shared
make -C include
make -C progs tic
install -v -m755 progs/tic /cross-tools/bin

cd $BUILD
rm -rvf $BUILD/*

#################################################################################
5.9. GMP-5.0.4 
####################################

tar -xvpf $SRC/gmp-5.0.4.tar.xz -C $BUILD
cd $BUILD/gmp-5.0.4

CPPFLAGS=-fexceptions ./configure --prefix=/cross-tools --enable-cxx
make -j32
make install

cd $BUILD
rm -rvf $BUILD/*

#################################################################################
5.10. MPFR-3.1.0
######################################

tar -xvpf $SRC/mpfr-3.1.0.tar.bz2 -C $BUILD
cd $BUILD/mpfr-3.1.0


LDFLAGS="-Wl,-rpath,/cross-tools/lib" ./configure --prefix=/cross-tools \
    --enable-shared --with-gmp=/cross-tools

make -j32
make install

cd $BUILD
rm -rvf $BUILD/*

#################################################################################

tar -xvpf $SRC/mpfr-3.1.0.tar.bz2 -C $BUILD
cd $BUILD/mpfr-3.1.0


LDFLAGS="-Wl,-rpath,/cross-tools/lib" ./configure --prefix=/cross-tools \
    --enable-shared --with-gmp=/cross-tools

make -j32
make install



#################################################################################

tar -xvpf $SRC/ppl-0.11.2.tar.bz2 -C $BUILD
cd $BUILD/ppl-0.11.2
CPPFLAGS="-I/cross-tools/include" \
    LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
    ./configure --prefix=/cross-tools --enable-shared \
    --enable-interfaces="c,cxx" --disable-optimization \
    --with-libgmp-prefix=/cross-tools \
    --with-libgmpxx-prefix=/cross-tools

make -j32 && make install 

cd $BUILD
rm -rvf $BUILD/*


#################################################################################

tar -xvpf $SRC/cloog-0.16.3.tar.gz -C $BUILD
cd $BUILD/cloog-0.16.3

cp -v configure{,.orig}
sed -e "/LD_LIBRARY_PATH=/d" configure.orig > configure

LDFLAGS="-Wl,-rpath,/cross-tools/lib" ./configure --prefix=/cross-tools --enable-shared --with-gmp-prefix=/cross-tools

make
make install

cd $BUILD
rm -rvf $BUILD/*

#################################################################################

tar -xvpf $SRC/binutils-2.22.tar.bz2 -C $BUILD
mkdir -v $BUILD/binutils-2.22/build
cd $BUILD/binutils-2.22/build/

AR=ar AS=as ../configure --prefix=/cross-tools --host=${CLFS_HOST} --target=${CLFS_TARGET} --with-sysroot=${CLFS} --with-lib-path=/tools/lib --disable-nls --enable-shared --enable-64-bit-bfd --disable-multilib --with-ppl=/cross-tools \
  --with-cloog=/cross-tools --enable-cloog-backend=isl

make configure-host
make -j32  
make install

cp -v ../include/libiberty.h /tools/include

cd $BUILD
rm -rvf $BUILD/*

#################################################################################

tar -xvpf $SRC/gcc-4.6.2.tar.bz2 -C $BUILD
mkdir -v $BUILD/gcc-4.6.2/build

cd $BUILD/gcc-4.6.2/gcc/config/

for file in `find . | grep ".h"`  ; do sed -i.org 's@\/lib64@\/tools@g' $file; done
for file in `find . | grep ".h"`  ; do sed -i.org 's@\/lib@\/tools@g' $file; done

rm -v `find . | grep ".org"`

cd $BUILD/gcc-4.6.2/

echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h

cp -v gcc/Makefile.in{,.orig}
sed -e "s@\(^CROSS_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g" \
    gcc/Makefile.in.orig > gcc/Makefile.in

touch /tools/include/limits.h

cd build

AR=ar LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
  ../configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --host=${CLFS_HOST} --target=${CLFS_TARGET} \
  --with-sysroot=${CLFS} --with-local-prefix=/tools --disable-nls \
  --disable-shared --with-mpfr=/cross-tools --with-gmp=/cross-tools \
  --with-ppl=/cross-tools --with-cloog=/cross-tools \
  --without-headers --with-newlib --disable-decimal-float \
  --disable-libgomp --disable-libmudflap --disable-libssp \
  --disable-threads --enable-languages=c --disable-multilib \
  --enable-cloog-backend=isl

make all-gcc all-target-libgcc -j32
make install-gcc install-target-libgcc -j32



###############################################################################################################
tar -xvpf $SRC/eglibc-2.15-r17386.tar.bz2  -C $BUILD
mkdir $BUILD/eglibc-2.15/build
cd $BUILD/eglibc-2.15

cp -v Makeconfig{,.orig}
sed -e 's/-lgcc_eh//g' Makeconfig.orig > Makeconfig

cd $BUILD/eglibc-2.15/build

cat > config.cache << "EOF"
libc_cv_forced_unwind=yes
libc_cv_c_cleanup=yes
libc_cv_gnu89_inline=yes
libc_cv_ssp=no
EOF

BUILD_CC="gcc" CC="${CLFS_TARGET}-gcc ${BUILD64}" \
      AR="${CLFS_TARGET}-ar" RANLIB="${CLFS_TARGET}-ranlib" \
      ../configure --prefix=/tools \
      --host=${CLFS_TARGET} --build=${CLFS_HOST} \
      --disable-profile --enable-add-ons \
      --with-tls --enable-kernel=2.6.0 --with-__thread \
      --with-binutils=/cross-tools/bin --with-headers=/tools/include \
      --cache-file=config.cache

make -j32
make install inst_vardbdir=/tools/var/db 

##################################################################################################


tar -xvpf $SRC/gcc-4.6.2.tar.bz2 -C $BUILD
mkdir -v $BUILD/gcc-4.6.2/build

cd $BUILD/gcc-4.6.2/gcc/config/

for file in `find . | grep ".h"`  ; do sed -i.org 's@\/lib64@\/tools@g' $file; done
for file in `find . | grep ".h"`  ; do sed -i.org 's@\/lib@\/tools@g' $file; done

rm -v `find . | grep ".org"`

cd $BUILD/gcc-4.6.2/

echo -en '#undef STANDARD_INCLUDE_DIR\n#define STANDARD_INCLUDE_DIR "/tools/include/"\n\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_1\n#define STANDARD_STARTFILE_PREFIX_1 "/tools/lib/"\n' >> gcc/config/linux.h
echo -en '\n#undef STANDARD_STARTFILE_PREFIX_2\n#define STANDARD_STARTFILE_PREFIX_2 ""\n' >> gcc/config/linux.h

cp -v gcc/Makefile.in{,.orig}
sed -e "s@\(^CROSS_SYSTEM_HEADER_DIR =\).*@\1 /tools/include@g" \
    gcc/Makefile.in.orig > gcc/Makefile.in

touch /tools/include/limits.h

cd $BUILD/gcc-4.6.2/build

AR=ar LDFLAGS="-Wl,-rpath,/cross-tools/lib" \
  ../gcc-4.6.2/configure --prefix=/cross-tools \
  --build=${CLFS_HOST} --target=${CLFS_TARGET} --host=${CLFS_HOST} \
  --with-sysroot=${CLFS} --with-local-prefix=/tools --disable-nls \
  --enable-shared --enable-languages=c,c++ --enable-__cxa_atexit \
  --with-mpfr=/cross-tools --with-gmp=/cross-tools --enable-c99 \
  --with-ppl=/cross-tools --with-cloog=/cross-tools --enable-cloog-backend=isl \
  --enable-long-long --enable-threads=posix --disable-multilib


make AS_FOR_TARGET="${CLFS_TARGET}-as" LD_FOR_TARGET="${CLFS_TARGET}-ld"
make install












