#!/bin/sh

###############################################################################
prep env
#################################

export TMPOS=/mnt/clfs
export SRC=$TMPOS/sources
export BUILD=$TMPOS/sources/build


install -dv $TMPOS/
install -dv $TMPOS/tools
install -dv $TMPOS/sources
install -dv $TMPOS/sources/build
install -dv $TMPOS/cross-tools


ln -sv $TMPOS/tools /
ln -sv $TMPOS/cross-tools /

chown -Rv clfs:clfs ${TMPOS}/sources
chown -Rv clfs:clfs ${TMPOS}/tools
chown -Rv clfs:clfs ${TMPOS}/cross-tools

groupadd clfs
useradd -s /bin/bash -g clfs -d /home/clfs clfs
mkdir -pv /home/clfs
chown -v clfs:clfs /home/clfs



cat > ~/.bash_profile << "EOF"
exec env -i HOME=${HOME} TERM=${TERM} PS1='\u:\w\$ ' /bin/bash
EOF

cat > ~/.bashrc << "EOF"
set +h
umask 022
TMPOS=/mnt/clfs

LC_ALL=POSIX
PATH=/cross-tools/bin:/bin:/usr/bin:/tools/bin:/tools/sbin:/sbin:/usr/sbin:
export CLFS LC_ALL PATH
EOF

source ~/.bash_profile
######################################################################################


unset CFLAGS
unset CXXFLAGS

echo unset CFLAGS >> ~/.bashrc
echo unset CXXFLAGS >> ~/.bashrc
export CLFS_HOST=$(echo ${MACHTYPE} | sed -e 's/-[^-]*/-cross/')

cat >> ~/.bashrc << EOF
export CLFS_HOST="${CLFS_HOST}"
export CLFS_TARGET="mips64el-neokylin-linux-gnu"
export CLFS_TARGET32="mipsel-neokylin-linux-gnu"
export BUILD32="-mabi=32"
export BUILDN32="-mabi=n32"
export BUILD64="-mabi=64"
EOF


source ~/.bash_profile

###############################################################################


